Fix/inbox UI enhancement
martian-st/march pull request #279
Opened 2024-10-11 16:02 UTC by deewakar-k

2024-10-11 16:15 UTC, oliursahin requested changes
- [x]     its showing all icons by default, where it should show by default.
- [x] no need to change the move icon
- [x] the small source icon can be hidden now, dont add a placeholder until functional. it looks ungy.
- [x]     the menu is opening in wrong place.
- [x] fix menu for mac user

2024-10-11 17:31 UTC, deewakar-k commented
> * [x]      its showing all icons by default, where it should show by default.
> 
>     * [x]  no need to change the move icon
> 
>     * [x]  the small source icon can be hidden now, dont add a placeholder until functional. it looks ungy.
> 
>     * [x]      the menu is opening in wrong place.
> 
>     * [x]  fix menu for mac user

done

2024-10-11 18:15 UTC, oliursahin submitted a review, later dismissed

2024-10-12 07:50 UTC, madhav-relish requested changes
Can you check this also, if an item is selected and we click on that again and again, every time an api is being triggered. 


https://github.com/user-attachments/assets/5eb011e4-bf18-4473-b72d-04153eb07fa7

2024-10-12 07:50 UTC, madhav-relish commented on apps/frontend/src/components/Inbox/InboxItems.tsx
> +      setOpenDropdownId(item._id)
You'll need to add null here in or condition

![image](https://github.com/user-attachments/assets/022dd793-c001-428f-b0c6-bd244299ca8f)

2024-10-12 07:50 UTC, madhav-relish commented on apps/frontend/src/components/Inbox/InboxItems.tsx
> +  }, [isFetched, fetchInbox])
Add proper error logging for better debugging like
console.error("Error from fetchInbox::", error)

2024-10-12 07:51 UTC, madhav-relish commented
@oliursahin  what do you think about this component? https://ui.shadcn.com/docs/components/drawer

It will be great for mobile devices as well right out of the box

2024-10-12 16:52 UTC, deewakar-k commented
> Can you check this also, if an item is selected and we click on that again and again, every time an api is being triggered. 
> 
> 
> 
> 
> 
> https://github.com/user-attachments/assets/5eb011e4-bf18-4473-b72d-04153eb07fa7
> 
> 
> 
> 

i believe this is the pr for ui not the integration

2024-10-14 06:16 UTC, sajdakabir commented
> > Can you check this also, if an item is selected and we click on that again and again, every time an api is being triggered.
> > 
> >   
> >     
> >     
> > 
> >     Screen.Recording.2024-10-12.131732.mp4
> 
> i believe this is the pr for ui not the integration, integration was done in earlier prs


so what? you can fix it, isn't it?!  @deewakar-k

2024-10-14 15:54 UTC, madhav-relish approved these changes, later dismissed

2024-10-14 17:08 UTC, merged